# Generated by Django 5.2.17 on 2026-08-21 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_date', models.DateField(verbose_name='受取日')),
                ('code', models.CharField(max_length=10, verbose_name='銘柄コード')),
                ('name', models.CharField(max_length=100, verbose_name='銘柄名')),
                ('amount', models.PositiveIntegerField(verbose_name='受取額 (税引後・円)')),
                ('memo', models.CharField(blank=True, default='', max_length=200, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_dividends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField(verbose_name='約定日')),
                ('code', models.CharField(max_length=10, verbose_name='銘柄コード')),
                ('name', models.CharField(max_length=100, verbose_name='銘柄名')),
                ('side', models.CharField(choices=[('buy', '買付'), ('sell', '売却')], max_length=4, verbose_name='売買')),
                ('quantity', models.PositiveIntegerField(verbose_name='株数')),
                ('price', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='単価')),
                ('fee', models.PositiveIntegerField(default=0, verbose_name='手数料 (円)')),
                ('account_type', models.CharField(choices=[('tokutei', '特定'), ('nisa_growth', 'NISA成長'), ('nisa_tsumitate', 'NISAつみたて'), ('ippan', '一般')], default='tokutei', max_length=14, verbose_name='口座区分')),
                ('broker', models.CharField(blank=True, default='', max_length=50, verbose_name='証券会社')),
                ('memo', models.CharField(blank=True, default='', max_length=200, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-trade_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='銘柄コード')),
                ('price', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='現在値')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_prices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'code'), name='uniq_user_stock_price')],
            },
        ),
    ]
