# Generated by Django 5.2.17 on 2026-08-21 13:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='import_key',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='取込キー'),
        ),
        migrations.AddConstraint(
            model_name='trade',
            constraint=models.UniqueConstraint(condition=models.Q(('import_key__isnull', False)), fields=('user', 'import_key'), name='uniq_user_trade_import_key'),
        ),
    ]
