# Generated by Django 5.2.17 on 2026-08-21 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_trade_import_key_trade_uniq_user_trade_import_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='銘柄コード')),
                ('name', models.CharField(max_length=100, verbose_name='銘柄名')),
                ('kind', models.CharField(choices=[('buy', '買い目標'), ('sell', '売り目標')], default='buy', max_length=4, verbose_name='種別')),
                ('target_price', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='目標価格')),
                ('memo', models.CharField(blank=True, default='', max_length=200, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_watches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='銘柄コード')),
                ('settlement_month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='決算月')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_infos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'code'), name='uniq_user_stock_info')],
            },
        ),
    ]
