# Generated by Django 5.2.17 on 2026-08-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_watch_stockinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividend',
            name='gross_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='配当金 (税引前・円)'),
        ),
        migrations.AddField(
            model_name='dividend',
            name='shares',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='配当対象株数'),
        ),
        migrations.AddField(
            model_name='dividend',
            name='tax_local',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='源泉徴収額 地方税 (円)'),
        ),
        migrations.AddField(
            model_name='dividend',
            name='tax_national',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='源泉徴収額 国税 (円)'),
        ),
    ]
