# Generated by Django 5.2.17 on 2026-08-21 23:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_dividend_gross_amount_dividend_shares_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dividend',
            name='import_key',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='取込キー'),
        ),
        migrations.AddConstraint(
            model_name='dividend',
            constraint=models.UniqueConstraint(condition=models.Q(('import_key__isnull', False)), fields=('user', 'import_key'), name='uniq_user_dividend_import_key'),
        ),
    ]
