# Generated by Django 5.2.17 on 2026-08-21 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_dividend_import_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividend',
            name='currency',
            field=models.CharField(default='円', max_length=10, verbose_name='受取通貨'),
        ),
        migrations.AlterField(
            model_name='dividend',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='受取額 (税引後)'),
        ),
        migrations.AlterField(
            model_name='dividend',
            name='gross_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='配当金 (税引前)'),
        ),
        migrations.AlterField(
            model_name='dividend',
            name='tax_local',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='源泉徴収額 地方税'),
        ),
        migrations.AlterField(
            model_name='dividend',
            name='tax_national',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='源泉徴収額 国税'),
        ),
    ]
