# Generated by Django 5.2.17 on 2026-08-21 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_merchantrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantrule',
            name='recurring_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchant_rules', to='ledger.recurringpayment'),
        ),
    ]
