# Generated by Django 5.2.17 on 2026-08-21 12:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_preference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='merchantrule',
            name='uniq_user_merchant',
        ),
        migrations.AddField(
            model_name='merchantrule',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='金額'),
        ),
        migrations.AddConstraint(
            model_name='merchantrule',
            constraint=models.UniqueConstraint(fields=('user', 'merchant', 'amount'), name='uniq_user_merchant_amount'),
        ),
    ]
