# Generated by Django 5.2.17 on 2026-08-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_remove_merchantrule_uniq_user_merchant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='forecast_expense',
            field=models.BooleanField(default=False, verbose_name='支払合計を予想で表示'),
        ),
    ]
